{
  "type": "record",
  "name": "OrderRejected",
  "namespace": "com.pulsedesk.contracts.events",
  "fields": [
    {
      "name": "eventId",
      "type": "string"
    },
    {
      "name": "orderId",
      "type": "string"
    },
    {
      "name": "userId",
      "type": "string"
    },
    {
      "name": "symbol",
      "type": "string"
    },
    {
      "name": "side",
      "type": {
        "type": "enum",
        "name": "RejectedOrderSide",
        "symbols": [
          "BUY",
          "SELL"
        ]
      }
    },
    {
      "name": "quantity",
      "type": "long"
    },
    {
      "name": "reason",
      "type": "string"
    },
    {
      "name": "timestamp",
      "type": "string"
    }
  ]
}
