name: pulsedesk

services:

  postgres:
    image: postgres:17-alpine
    container_name: pulsedesk-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB:-pulsedesk}
      POSTGRES_USER: ${POSTGRES_USER:-pulsedesk}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pulsedesk_dev_password}

    ports:
      - "${POSTGRES_PORT:-5432}:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./infrastructure/postgres/init:/docker-entrypoint-initdb.d:ro

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

    networks:
      - pulsedesk-network


  kafka-volume-init:
    image: alpine:3.22
    container_name: pulsedesk-kafka-volume-init
    user: "0:0"

    command:
      - /bin/sh
      - -c
      - |
        echo "Ajustando permissões do volume Kafka..."
        chown -R 1000:1000 /kafka-data
        chmod -R u+rwX /kafka-data
        echo "Permissões ajustadas."

    volumes:
      - kafka-data:/kafka-data

    networks:
      - pulsedesk-network


  kafka:
    image: apache/kafka:4.3.1
    container_name: pulsedesk-kafka
    hostname: kafka
    restart: unless-stopped

    depends_on:
      kafka-volume-init:
        condition: service_completed_successfully

    ports:
      - "${KAFKA_EXTERNAL_PORT:-9092}:9092"

    environment:
      KAFKA_NODE_ID: 1

      KAFKA_PROCESS_ROLES: "broker,controller"

      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
        CONTROLLER:PLAINTEXT,
        INTERNAL:PLAINTEXT,
        EXTERNAL:PLAINTEXT

      KAFKA_LISTENERS: >
        CONTROLLER://:29093,
        INTERNAL://:19092,
        EXTERNAL://:9092

      KAFKA_ADVERTISED_LISTENERS: >
        INTERNAL://kafka:19092,
        EXTERNAL://localhost:9092

      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      CLUSTER_ID: "4L6g3nShT-eMCtK--X86sw"

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_SHARE_COORDINATOR_STATE_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_SHARE_COORDINATOR_STATE_TOPIC_MIN_ISR: 1

      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"

    volumes:
      - kafka-data:/tmp/kraft-combined-logs

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list > /dev/null 2>&1"
        ]
      interval: 5s
      timeout: 10s
      retries: 15
      start_period: 20s

    networks:
      - pulsedesk-network

  schema-registry:
    image: confluentinc/cp-schema-registry:8.3.1
    container_name: pulsedesk-schema-registry
    hostname: schema-registry
    restart: unless-stopped

    depends_on:
      kafka:
        condition: service_healthy

    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:19092

    ports:
      - "8085:8081"

    networks:
      - pulsedesk-network

  kafka-init:
    image: apache/kafka:4.3.1
    container_name: pulsedesk-kafka-init

    depends_on:
      kafka:
        condition: service_healthy

    entrypoint: ["/bin/bash", "-c"]

    command:
      - |
        set -e

        echo "Aguardando conexão com o Kafka..."

        until /opt/kafka/bin/kafka-topics.sh \
          --bootstrap-server kafka:19092 \
          --list >/dev/null 2>&1;
        do
          echo "Kafka ainda não está disponível..."
          sleep 2
        done

        echo "Kafka disponível. Criando tópicos..."

        for topic in \
          market-data.updated \
          order.created \
          order.executed \
          order.rejected \
          portfolio.updated
        do
          echo "Criando tópico: $${topic}"

          /opt/kafka/bin/kafka-topics.sh \
            --bootstrap-server kafka:19092 \
            --create \
            --if-not-exists \
            --topic "$${topic}" \
            --partitions 1 \
            --replication-factor 1
        done

        echo "Tópicos existentes:"

        /opt/kafka/bin/kafka-topics.sh \
          --bootstrap-server kafka:19092 \
          --list

    networks:
      - pulsedesk-network


  market-data-service:
    build:
      context: .
      dockerfile: backend/market-data-service/Dockerfile

    container_name: pulsedesk-market-data-service
    restart: unless-stopped

    depends_on:
      kafka:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully

    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:19092
      SCHEMA_REGISTRY_URL: http://schema-registry:8081
      FINNHUB_API_KEY: ${FINNHUB_API_KEY}

    ports:
      - "8081:8081"

    networks:
      - pulsedesk-network


  trading-service:
    build:
      context: .
      dockerfile: backend/trading-service/Dockerfile

    container_name: pulsedesk-trading-service
    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully

    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:19092
      SCHEMA_REGISTRY_URL: http://schema-registry:8081

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pulsedesk?currentSchema=trading
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-pulsedesk}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-pulsedesk_dev_password}

    ports:
      - "8082:8082"

    networks:
      - pulsedesk-network


  portfolio-service:
    build:
      context: .
      dockerfile: backend/portfolio-service/Dockerfile

    container_name: pulsedesk-portfolio-service
    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully

    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:19092
      SCHEMA_REGISTRY_URL: http://schema-registry:8081

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pulsedesk?currentSchema=portfolio
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-pulsedesk}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-pulsedesk_dev_password}

    ports:
      - "8083:8083"

    networks:
      - pulsedesk-network


  websocket-gateway:
    build:
      context: ./backend/websocket-gateway
      dockerfile: Dockerfile

    container_name: pulsedesk-websocket-gateway
    restart: unless-stopped

    depends_on:
      kafka:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully

    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:19092

    ports:
      - "8084:8084"

    networks:
      - pulsedesk-network


  frontend:
    build:
      context: ./frontend/pulsedesk-ui
      dockerfile: Dockerfile

    container_name: pulsedesk-frontend
    restart: unless-stopped

    environment:
      NG_ALLOWED_HOSTS: "localhost,127.0.0.1"

    ports:
      - "4200:4200"

    networks:
      - pulsedesk-network

volumes:

  postgres-data:
    name: pulsedesk-postgres-data

  kafka-data:
    name: pulsedesk-kafka-data


networks:

  pulsedesk-network:
    name: pulsedesk-network
