spring:
  application:
    name: market-data-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

    properties:
      "[schema.registry.url]": ${SCHEMA_REGISTRY_URL:http://localhost:8085}

server:
  port: ${SERVER_PORT:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info

finnhub:
  api-key: ${FINNHUB_API_KEY}

alpha-vantage:
  api-key: ${ALPHA_VANTAGE_API_KEY}
